--- 
- 
  ec2_ami_find: 
    name: "{{image_name}}"
    owner: "{{image_owner}}"
    region: "{{region}}"
    sort: name
    sort_end: 1
    sort_order: descending
  name: "find ami"
  register: ami_find
-
  debug: var=ami_find
- 
  ec2:
    assign_public_ip: "{{assign_public_ip}}"
    count: "{{count}}"
    group: "{{mygroup}}"
    image: "{{ ami_find.results[0].ami_id }}"
    instance_type: "{{instance_type}}"
    keypair: "{{keypair}}"
    region: "{{region}}"
    source_dest_check: "{{source_dest_check}}"
    vpc_subnet_id: "{{vpc_subnet_id}}"
    wait: "{{wait}}"
    instance_tags: "{{mytags}}"
  register: ec2_info
- 
  debug: var=ec2_info
- 
  debug: var=item
  with_items: "{{ec2_info.instance_ids}}"
- 
  add_host: "hostname={{item.private_ip}} groupname=tag_Name_{{mygroup}}"
  with_items: "{{ec2_info.instances}}"
- 
  name: "wait for instances to listen on port:22"
  wait_for: 
    host: "{{item.private_ip}}"
    port: 22
    state: started
  with_items: "{{ec2_info.instances}}"

